name: Deploy ngnix for Swagger Docs

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT}}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: build and push image
      env: 
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run:
        gcloud auth configue-docker asia-south1-docker.pkg.dev
        docker build -t asia-south1-docker.pkg.dev/projectsprod-418002/swagger-demo/nginx:latest .
        docker push asia-south1-docker.pkg.dev/projectsprod-418002/swagger-demo/nginx:latest